### ISSUE TITLE
Mini JavaScript Project

### ISSUE THREAD

**Issue by shivanshi-s** [bhavberi/Hactoberfest-2022-Beginners#15]
Hey,  I want to contribute javascript project in the repo. Is it allowed? Could you guide me to the next steps as well? thanks!

**Comment by Adityasaini10012001** [comment]
please assign this to me I want to contribute to this.

**Comment by bhavberi** [comment]
@shivanshi-s Yes you can anytime contribute with any ~~basic~~ interesting project/program.

You can easily follow the steps given in Readme File for further steps.
