### ISSUE TITLE
Notes Taking Application

### ISSUE THREAD

**Issue by aditi072** [bhavberi/Hactoberfest-2022-Beginners#23]
Hey 👋 I wanted to contribute a notes taking application in java script , with a pretty frontend.
Please assign me to contribute to the repo.

**Comment by Adityasaini10012001** [comment]
hey @aditi072  are you working on this

**Comment by aditi072** [comment]
Hey It is completed. Please accept my pull request and merge it. This will be my first contribution! @bhavberi
