### ISSUE TITLE
Organizing the repo

### ISSUE THREAD

**Issue by AlvinManojAlex** [bhavberi/Hactoberfest-2022-Beginners#33]
I noticed that python's files are not in a proper directory. Structuring it by moving the python files to a directory can make for better readability.

I can do this as well (since I'm planning to add a python script to this repo myself)

**Comment by AlvinManojAlex** [comment]
#35

**Comment by AlvinManojAlex** [comment]
#35 Here's the PR for your convenience. ( never worked with issues before so the communication interface was tricky to get used to )

**Comment by bhavberi** [comment]
Yeah, Looks Nice!!
Also, hoping to see some nice applications from your end too soon.
