### ISSUE TITLE
Web project for MCQ Quiz Website

### ISSUE THREAD

**Issue by AlvinManojAlex** [bhavberi/Hactoberfest-2022-Beginners#43]
Hey! I have a web project that incorporates a quiz interface. I want to contribute this to this repo.

**Comment by AlvinManojAlex** [comment]
#50 Here's the PR

**Comment by Shubham-20205157** [comment]
Can You assign me this issue please, I want to contribute.

**Comment by bhavberi** [comment]
@Shubham-20205157 
You can anytime contribute with any amazing application (and not some DSA code).
